export const LOAD_NOTES_PENDING = "LOAD_NOTES_PENDING";
export const LOAD_NOTES_SUCCESS = "LOAD_NOTES_SUCCESS";
export const LOAD_NOTES_ERROR = "LOAD_NOTES_ERROR";

export const CREATE_NOTE_PENDING = "CREATE_NOTE_PENDING";
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS";
export const CREATE_NOTE_ERROR = "CREATE_NOTE_ERROR";

export const DELETE_NOTE = "DELETE_NOTE";
